#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# FlowFirst - Chrony (NTP) Time Synchronisation Setup for RHEL 9.6
#
# RabbitMQ cluster nodes MUST have synchronised clocks.  A clock drift of more
# than a few seconds causes:
#   - Erlang cookie / distribution handshake failures
#   - RabbitMQ cluster node rejections ("Net Ticktime" mismatches)
#   - X.509 / TLS certificate validation failures
#   - Galera wsrep certification errors
#   - Pacemaker stonith / quorum race conditions
#
# This script:
#   1. Installs chrony (already present on most RHEL 9 minimal installs)
#   2. Optionally sets a custom NTP server pool (default: pool.ntp.org)
#   3. Enables and starts chronyd
#   4. Forces an immediate time sync (chronyc makestep)
#   5. Prints current sync status and offset
#
# Usage:
#   sudo ./scripts/setup_chronyd.sh [NTP_SERVER]
#
# Examples:
#   sudo ./scripts/setup_chronyd.sh                   # use pool.ntp.org
#   sudo ./scripts/setup_chronyd.sh 192.168.1.1       # use local NTP server
#   sudo ./scripts/setup_chronyd.sh time.google.com   # use Google NTP
# ==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Source .env if present
if [ -f "${ROOT_DIR}/.env" ]; then
    # shellcheck disable=SC1091
    set -a
    source "${ROOT_DIR}/.env"
    set +a
fi

NTP_SERVER="${1:-${CHRONY_NTP_SERVER:-pool.ntp.org}}"

echo "=================================================================="
echo " FlowFirst - Chrony Time Sync Setup"
echo " NTP Server: ${NTP_SERVER}"
echo "=================================================================="

# ---------------------------------------------------------------------------
# Step 1: Install chrony
# ---------------------------------------------------------------------------
echo "[1/5] Installing chrony..."
if rpm -q chrony >/dev/null 2>&1; then
    echo "  chrony is already installed — skipping."
else
    sudo dnf install -y chrony
    echo "  chrony installed."
fi

# ---------------------------------------------------------------------------
# Step 2: Configure NTP server
# ---------------------------------------------------------------------------
echo "[2/5] Configuring NTP server (${NTP_SERVER})..."
CHRONY_CONF="/etc/chrony.conf"

# Back up original config once
if [ ! -f "${CHRONY_CONF}.flowfirst.bak" ]; then
    sudo cp "${CHRONY_CONF}" "${CHRONY_CONF}.flowfirst.bak"
    echo "  Backup saved to ${CHRONY_CONF}.flowfirst.bak"
fi

# Remove existing pool/server lines and prepend our server at the top
sudo tee "${CHRONY_CONF}" > /dev/null << EOF
# FlowFirst managed chrony configuration
# Generated by scripts/setup_chronyd.sh
# Original backup: ${CHRONY_CONF}.flowfirst.bak

# Primary NTP server
server ${NTP_SERVER} iburst prefer

# Fallback public pool (comment out if on isolated network)
pool pool.ntp.org iburst

# Record the rate at which the system clock gains/loses time.
driftfile /var/lib/chrony/drift

# Allow the system clock to be stepped in the first three updates
# if its offset is larger than 1 second.
makestep 1.0 3

# Enable kernel synchronisation of the real-time clock (RTC).
rtcsync

# Allow NTP client access from the cluster subnet (for nodes that
# cannot reach the internet and use this node as a local source).
# allow 192.168.1.0/24

# Specify file containing keys for NTP authentication.
keyfile /etc/chrony.keys

# Specify the key used as password for chronyc.
commandkey 1

# Get TAI-UTC offset and leap seconds from the system tz database.
leapsectz right/UTC

# Specify directory for log files.
logdir /var/log/chrony
EOF
echo "  ${CHRONY_CONF} written."

# ---------------------------------------------------------------------------
# Step 3: Enable and start chronyd
# ---------------------------------------------------------------------------
echo "[3/5] Enabling and starting chronyd..."
sudo systemctl enable chronyd
sudo systemctl restart chronyd
echo "  chronyd enabled and running."

# ---------------------------------------------------------------------------
# Step 4: Force an immediate step sync (do not wait for gradual slew)
# ---------------------------------------------------------------------------
echo "[4/5] Forcing immediate time step (chronyc makestep)..."
sleep 2   # give chronyd a moment to contact the server
sudo chronyc makestep || echo "  Warning: makestep returned non-zero (clock may already be correct)"
echo "  Time step applied."

# ---------------------------------------------------------------------------
# Step 5: Print sync status
# ---------------------------------------------------------------------------
echo "[5/5] Current synchronisation status:"
echo ""
sudo chronyc tracking
echo ""
echo "  Reference sources:"
sudo chronyc sources -v | head -20
echo ""

# Final check: warn if not synchronised
SYNCED=$(chronyc tracking 2>/dev/null | grep "^System time" || true)
LEAP=$(chronyc tracking 2>/dev/null | grep "^Leap status" | awk '{print $NF}' || true)

if [ "${LEAP}" = "Normal" ] || [ "${LEAP}" = "Not synchronised" ]; then
    if [ "${LEAP}" != "Normal" ]; then
        echo "WARNING: chrony reports '${LEAP}' — clock may not yet be synchronised."
        echo "         Wait 30–60 seconds and re-run: chronyc tracking"
    fi
fi

echo ""
echo "=================================================================="
echo " Chrony setup complete."
echo " Verify offset before starting RabbitMQ:"
echo "   chronyc tracking | grep 'System time'"
echo "   # offset should be well under 1 second"
echo "=================================================================="
